cache: bundler
sudo: false
script: "bundle exec rake"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
gemfile:
  - gemfiles/Gemfile.rails-3.2.22
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-edge
    - gemfile: gemfiles/Gemfile.rails-3.2.22
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.rails-edge
